//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazadbMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int PersonelNo { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelAdres { get; set; }
        public string PersonelTelefon { get; set; }
        public Nullable<int> MagazaNo { get; set; }
    
        public virtual Magaza Magaza { get; set; }
    }
}
